server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only scrape containers with specific labels
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      # Parse JSON logs from Konsul
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            service: service
      - labels:
          level:
          service:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: msg

  # Scrape specific Konsul container
  - job_name: konsul
    static_configs:
      - targets:
          - localhost
        labels:
          job: konsul
          service: konsul
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            method: method
            path: path
            status: status
            duration: duration
      - labels:
          level:
          method:
          path:
          status:
      - timestamp:
          source: time
          format: RFC3339Nano
