# Application Environment Configuration
# Generated by konsul-template

# Database Configuration
DB_HOST={{ kv "config/database/host" }}
DB_PORT={{ kv "config/database/port" }}
DB_NAME={{ kv "config/database/name" }}
DB_USER={{ kv "config/database/user" }}

# Redis Configuration
{{- if kv "config/redis/host" }}
REDIS_HOST={{ kv "config/redis/host" }}
REDIS_PORT={{ kv "config/redis/port" }}
{{- end }}

# Service URLs
{{- range services }}
SERVICE_{{ toUpper .Name }}_URL=http://{{ .Address }}:{{ .Port }}
{{- end }}

# Environment
NODE_ENV={{ env "NODE_ENV" }}
LOG_LEVEL={{ kv "config/log_level" }}
