# Generated by konsul-template
# DO NOT EDIT MANUALLY

{{- $domain := kv "config/domain" }}

upstream backend {
    {{- range service "web" }}
    server {{ .Address }}:{{ .Port }} max_fails=3 fail_timeout=30s;
    {{- end }}
}

upstream api_backend {
    {{- range service "api" }}
    server {{ .Address }}:{{ .Port }} max_fails=3 fail_timeout=30s;
    {{- end }}
}

server {
    listen 80;
    server_name {{ $domain }};

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api {
        proxy_pass http://api_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
    }
}
