apiVersion: v1
kind: ServiceAccount
metadata:
  name: konsul
  namespace: konsul
  labels:
    app.kubernetes.io/name: konsul
    app.kubernetes.io/component: service-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: konsul
  namespace: konsul
  labels:
    app.kubernetes.io/name: konsul
    app.kubernetes.io/component: service-discovery
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: konsul
  namespace: konsul
  labels:
    app.kubernetes.io/name: konsul
    app.kubernetes.io/component: service-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: konsul
subjects:
- kind: ServiceAccount
  name: konsul
  namespace: konsul
