apiVersion: v1
kind: Service
metadata:
  name: konsul
  namespace: konsul
  labels:
    app.kubernetes.io/name: konsul
    app.kubernetes.io/component: service-discovery
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8888
    targetPort: http
    protocol: TCP
  - name: dns-tcp
    port: 8600
    targetPort: dns-tcp
    protocol: TCP
  - name: dns-udp
    port: 8600
    targetPort: dns-udp
    protocol: UDP
  selector:
    app.kubernetes.io/name: konsul
---
apiVersion: v1
kind: Service
metadata:
  name: konsul-headless
  namespace: konsul
  labels:
    app.kubernetes.io/name: konsul
    app.kubernetes.io/component: service-discovery
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8888
    targetPort: http
    protocol: TCP
  - name: dns-tcp
    port: 8600
    targetPort: dns-tcp
    protocol: TCP
  - name: dns-udp
    port: 8600
    targetPort: dns-udp
    protocol: UDP
  selector:
    app.kubernetes.io/name: konsul
