# Default values for konsul.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replica configuration
replicaCount: 1

# Container image configuration
image:
  repository: konsul
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Image pull secrets for private registries
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security contexts
podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 8888
  targetPort: 8888
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: konsul.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: konsul-tls
  #    hosts:
  #      - konsul.example.com

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /services/
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /services/
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selection and affinity
nodeSelector: {}
tolerations: []
affinity: {}

# Konsul-specific configuration
konsul:
  # Server configuration
  host: ""  # Empty means all interfaces
  port: 8888

  # Service discovery settings
  serviceTTL: "30s"
  cleanupInterval: "60s"

  # Logging configuration
  logLevel: "info"  # debug, info, warn, error
  logFormat: "json"  # text, json

  # Persistence configuration
  persistence:
    enabled: true
    type: "badger"  # memory, badger
    storageClass: ""  # Use default storage class if not specified
    size: "1Gi"
    # Mount path inside the container
    dataDir: "/app/data"
    backupDir: "/app/backups"

    # BadgerDB specific settings
    syncWrites: true
    walEnabled: true

  # Environment variables (additional)
  env: []
  # - name: CUSTOM_ENV
  #   value: "value"

  # Extra configuration via ConfigMap
  configMap:
    enabled: false
    data: {}
    # key1: value1
    # key2: value2

# Volume mounts for the container
volumeMounts:
  - name: data
    mountPath: /app/data
  - name: backup
    mountPath: /app/backups
  - name: tmp
    mountPath: /tmp

# Volumes configuration
volumes:
  - name: tmp
    emptyDir: {}

# Monitoring and metrics
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    labels: {}

# Network policies
networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: konsul-client
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: konsul