{{- if .Values.konsul.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "konsul.fullname" . }}
  labels:
    {{- include "konsul.labels" . | nindent 4 }}
data:
  {{- with .Values.konsul.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}